### ISSUE TITLE
Clicking play on songs/artists doesn't do anything.

### ISSUE THREAD

**Issue by jespeer** [SCCapstone/DKMS#341] opened 2023-04-10 19:53 UTC
https://user-images.githubusercontent.com/70123091/230985732-66c914bf-f878-4217-94f5-1f04b877749f.mp4

Steps to Reproduce:
Log in
Click on Profile
Click on the play button for any of the squares.

**Comment by cravend** [comment] 2023-04-13 19:53
See the note in #343

**Comment by cravend** [comment] 2023-04-16 14:40
Duplicate of #343

**Closed by cravend** 2023-04-16 14:40 UTC
Labels: bug, qa
