### ISSUE TITLE
Too broad of a search creates issues with the Search Tab

### ISSUE THREAD

**Issue by Twofishsticks** [SCCapstone/DKMS#333] opened 2023-04-08 17:48 UTC
When using some broad search terms, such as "beatles" or "star wars", the search tab returns an error. However, more specific terms do not create the same form of error. 

https://user-images.githubusercontent.com/70028633/230735275-7779357b-607d-4954-a176-af445fa06b2a.mp4

Steps to Reproduce
- Login, Navigate to Search Tab
- Use some broad search term, such as Beatles, observe the error
- Use a more specific search term, such as The Beatles observe the populated results 
(refreshing entire page need not apply, using the try again button works)

See #321 as well.

**Comment by cravend** [comment] 2023-04-09 04:56
dev notes: this is 99% sure to be one of those Spotify CDN url errors.

**Comment by cravend** [comment] 2023-04-15 00:43
Duplicate of #321

**Closed by cravend** 2023-04-15 00:43 UTC
Labels: bug, qa
