### ISSUE TITLE
DKMS will not let users access ANY podcast

### ISSUE THREAD

**Issue by Twofishsticks** [SCCapstone/DKMS#358] opened 2023-04-16 19:34 UTC
https://user-images.githubusercontent.com/70028633/232337367-66b06a42-65b3-45fd-b6dd-2e591e141b0a.mp4

I've created a test playlist to help with finding this bug. It's labelled "Test Playlist", and has one song and one podcast. 

To replicate this bug 
- Try and type in **ANY** podcast name that can be found on Spotify 
- Observe the search bar breaks and throws up the "Something went wrong" screen. 
OR 
- Search for "Test Playlist", find the first option in the playlist section
- Attempt to open the playlist, get shown the error screen seen in #356 

Either way, it's impossible to find a track labelled as a "podcast" by Spotify within this application. Attempting to do so either turns up no results or an error screen.

**Comment by cravend** [comment] 2023-04-17 02:31
Duplicate of #356

**Closed by cravend** 2023-04-17 02:31 UTC
Labels: qa, duplicate
